### ISSUE TITLE
Token Interpolation not working as expected

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/esds-build#135]
Test the following in tokens.yaml

```
test-scenario:
  this: &test-this "Something"
  that: &test-that "Else"
  combined: "!{*test-this} !{*test-that}"
```

Should output in scss:
`$esds-test-scenario-combined: "Something Else";

But it doesn't
